backend: 
  name: git-gateway
  branch: master

media_folder: "_site/img/uploads"
public_folder: "img/uploads"

collections: 
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/posts.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "postDate", widget: "date", default:"" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage" widget: "image" }
